<%@page import="java.sql.Statement"%>
<%@page import="java.sql.DriverManager"%>
<%@page import="java.sql.Connection"%>
<%@page import="java.sql.PreparedStatement"%>
<%@page import="java.sql.ResultSet"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>

<jsp:useBean id="obj" class="Models.JobOffer" scope="session"/>
<jsp:setProperty property="*" name="obj"/>

<%
    try {
        Class.forName("oracle.jdbc.OracleDriver");
        Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "admin");
        Statement s = c.createStatement();
        ResultSet rs = s.executeQuery("SELECT count(*) FROM user_tables WHERE table_name = 'JOBOFFERS'");
        if (rs.next()) {
            int count = rs.getInt(1);
            if (count == 0) {
                s.executeUpdate("CREATE TABLE JobOffers (OfferID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, ApplicationID NUMBER, Details VARCHAR2(255), Approved CHAR(1))");
            }
        }
        PreparedStatement ps = c.prepareStatement("INSERT INTO JobOffers (ApplicationID, Details, Approved) VALUES (?, ?, ?)");

        ps.setInt(1, obj.getApplication().getId());
        ps.setString(2, obj.getDetails());
        ps.setString(3, obj.isApproved() ? "Y" : "N");
        ps.execute();
    } catch (Exception e) {
        e.printStackTrace();
    }
%>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Create Job Offer Page</title>
</head>
<body>
<h2>Create Job Offer Form</h2>
<form method="post" action="createJobOffer">
    <input type="hidden" name="applicationId" value="<%= obj.getApplication().getId() %>">
    <textarea name="details" placeholder="Offer Details" required></textarea><br>
    <label for="approved">Approved:</label><br>
    <select id="approved" name="approved">
        <option value="Y">Yes</option>
        <option value="N">No</option>
    </select><br>
    <input type="submit" value="Create Offer">
</form>
</body>
</html>
